// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {portcheck} from '../models';
import {phpswitch} from '../models';
import {downloader} from '../models';
import {config} from '../models';
import {configeditor} from '../models';
import {project} from '../models';
import {logs} from '../models';
import {ssl} from '../models';
import {services} from '../models';
import {vhost} from '../models';

export function AddPHPPath(arg1:string):Promise<void>;

export function AddVirtualHost(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ApplyProject(arg1:string):Promise<void>;

export function CancelBinaryDownload(arg1:string,arg2:string):Promise<void>;

export function CheckAllPortConflicts():Promise<Array<portcheck.ConflictInfo>>;

export function CheckPortConflict(arg1:number):Promise<portcheck.ConflictInfo>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean,arg7:Record<string, boolean>):Promise<void>;

export function DeactivateProject():Promise<void>;

export function DeleteBinary(arg1:string,arg2:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function GenerateSSLCert(arg1:string):Promise<void>;

export function GetActivePHP():Promise<phpswitch.PHPInstall>;

export function GetAdminerStatus():Promise<Record<string, any>>;

export function GetBinaryStatus():Promise<Array<downloader.ServiceVersionStatus>>;

export function GetCACertPath():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetConfigBackups(arg1:string):Promise<Array<configeditor.BackupInfo>>;

export function GetLogPaths():Promise<Record<string, Array<string>>>;

export function GetPHPInstalls():Promise<Array<phpswitch.PHPInstall>>;

export function GetProjects():Promise<Array<project.Project>>;

export function GetRecentLogs(arg1:string,arg2:number):Promise<Array<logs.LogEntry>>;

export function GetSSLCerts():Promise<Array<ssl.CertInfo>>;

export function GetServiceConfigs(arg1:string):Promise<Array<configeditor.ConfigFile>>;

export function GetServices():Promise<Array<services.ServiceInfo>>;

export function GetVersionCatalog():Promise<Record<string, downloader.ServiceCatalog>>;

export function GetVirtualHosts():Promise<Array<vhost.VirtualHost>>;

export function GetWWWPath():Promise<string>;

export function HideWindow():Promise<void>;

export function IsPortInUse(arg1:number):Promise<boolean>;

export function IsSSLCAInstalled():Promise<boolean>;

export function KillConflictProcess(arg1:number):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function QuickCreateProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<project.Project>;

export function ReadConfigFile(arg1:string):Promise<string>;

export function ReloadCatalog():Promise<void>;

export function RemoveSSLCert(arg1:string):Promise<void>;

export function RemoveVirtualHost(arg1:string):Promise<void>;

export function RestartService(arg1:string):Promise<void>;

export function RestoreConfigBackup(arg1:string,arg2:string):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveConfigFile(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SetActiveVersion(arg1:string,arg2:string):Promise<void>;

export function SetServiceEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ShowNotification(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAdminer():Promise<string>;

export function StartAll():Promise<void>;

export function StartBinaryDownload(arg1:string,arg2:string):Promise<void>;

export function StartLogWatch(arg1:string):Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAdminer():Promise<void>;

export function StopAll():Promise<void>;

export function StopLogWatch():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function SwitchPHP(arg1:string):Promise<void>;

export function TerminalClose():Promise<void>;

export function TerminalResize(arg1:number,arg2:number):Promise<void>;

export function TerminalStart(arg1:string):Promise<void>;

export function TerminalWrite(arg1:string):Promise<void>;

export function TrustSSLCA():Promise<void>;

export function UpdateProject(arg1:project.Project):Promise<void>;
