// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPHPPath(arg1) {
  return window['go']['main']['App']['AddPHPPath'](arg1);
}

export function AddVirtualHost(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddVirtualHost'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyProject(arg1) {
  return window['go']['main']['App']['ApplyProject'](arg1);
}

export function CancelBinaryDownload(arg1, arg2) {
  return window['go']['main']['App']['CancelBinaryDownload'](arg1, arg2);
}

export function CheckAllPortConflicts() {
  return window['go']['main']['App']['CheckAllPortConflicts']();
}

export function CheckPortConflict(arg1) {
  return window['go']['main']['App']['CheckPortConflict'](arg1);
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateProject(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function DeactivateProject() {
  return window['go']['main']['App']['DeactivateProject']();
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteBinary(arg1, arg2) {
  return window['go']['main']['App']['DeleteBinary'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function CompleteOnboarding() {
  return window['go']['main']['App']['CompleteOnboarding']();
}

export function GenerateSSLCert(arg1) {
  return window['go']['main']['App']['GenerateSSLCert'](arg1);
}

export function GetActivePHP() {
  return window['go']['main']['App']['GetActivePHP']();
}

export function GetAdminerStatus() {
  return window['go']['main']['App']['GetAdminerStatus']();
}

export function GetBinaryStatus() {
  return window['go']['main']['App']['GetBinaryStatus']();
}

export function GetCACertPath() {
  return window['go']['main']['App']['GetCACertPath']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function GetConfigBackups(arg1) {
  return window['go']['main']['App']['GetConfigBackups'](arg1);
}

export function GetLogPaths() {
  return window['go']['main']['App']['GetLogPaths']();
}

export function GetPHPInstalls() {
  return window['go']['main']['App']['GetPHPInstalls']();
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetRecentLogs(arg1, arg2) {
  return window['go']['main']['App']['GetRecentLogs'](arg1, arg2);
}

export function GetSSLCerts() {
  return window['go']['main']['App']['GetSSLCerts']();
}

export function GetServiceConfigs(arg1) {
  return window['go']['main']['App']['GetServiceConfigs'](arg1);
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetVersionCatalog() {
  return window['go']['main']['App']['GetVersionCatalog']();
}

export function GetVirtualHosts() {
  return window['go']['main']['App']['GetVirtualHosts']();
}

export function GetWWWPath() {
  return window['go']['main']['App']['GetWWWPath']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsPortInUse(arg1) {
  return window['go']['main']['App']['IsPortInUse'](arg1);
}

export function IsSSLCAInstalled() {
  return window['go']['main']['App']['IsSSLCAInstalled']();
}

export function KillConflictProcess(arg1) {
  return window['go']['main']['App']['KillConflictProcess'](arg1);
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function ListDatabases() {
  return window['go']['main']['App']['ListDatabases']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function QuickCreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QuickCreateProject'](arg1, arg2, arg3, arg4);
}

export function ReadConfigFile(arg1) {
  return window['go']['main']['App']['ReadConfigFile'](arg1);
}

export function ReloadCatalog() {
  return window['go']['main']['App']['ReloadCatalog']();
}

export function RemoveSSLCert(arg1) {
  return window['go']['main']['App']['RemoveSSLCert'](arg1);
}

export function RemoveVirtualHost(arg1) {
  return window['go']['main']['App']['RemoveVirtualHost'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RestoreConfigBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreConfigBackup'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveConfigFile(arg1, arg2) {
  return window['go']['main']['App']['SaveConfigFile'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetActiveVersion(arg1, arg2) {
  return window['go']['main']['App']['SetActiveVersion'](arg1, arg2);
}

export function SetAutoRecover(arg1, arg2) {
  return window['go']['main']['App']['SetAutoRecover'](arg1, arg2);
}

export function SetServiceEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetServiceEnabled'](arg1, arg2);
}

export function ShowNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowNotification'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartAdminer() {
  return window['go']['main']['App']['StartAdminer']();
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartBinaryDownload(arg1, arg2) {
  return window['go']['main']['App']['StartBinaryDownload'](arg1, arg2);
}

export function StartLogWatch(arg1) {
  return window['go']['main']['App']['StartLogWatch'](arg1);
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopAdminer() {
  return window['go']['main']['App']['StopAdminer']();
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopLogWatch() {
  return window['go']['main']['App']['StopLogWatch']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function SwitchPHP(arg1) {
  return window['go']['main']['App']['SwitchPHP'](arg1);
}

export function TerminalClose() {
  return window['go']['main']['App']['TerminalClose']();
}

export function TerminalResize(arg1, arg2) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2);
}

export function TerminalStart(arg1) {
  return window['go']['main']['App']['TerminalStart'](arg1);
}

export function TerminalWrite(arg1) {
  return window['go']['main']['App']['TerminalWrite'](arg1);
}

export function TrustSSLCA() {
  return window['go']['main']['App']['TrustSSLCA']();
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
